title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://rosesz.github.io/knowledge_base

aux_links:
  Template Repository: https://github.com/rosesz/knowledge_base
