title: Ruby Knowledge Base
description: Ruby Knowledge Base
theme: just-the-docs

url: https://rosesz.github.io/rubybase

aux_links:
  Template Repository: https://github.com/rosesz/rubybase

callouts:
  warning:
    title: Uwaga
    color: red
  note:
    title: Wskazówka
    color: purple
  highlight:
    title: Ćwiczenie
    color: yellow


