title: Ruby Knowledge Base
description: Ruby Knowledge Base
theme: just-the-docs
logo: "/images/logo.png"
favicon_ico: "/images/favicon.ico"
url: https://rosesz.github.io/rubybase

callouts:
  warning:
    title: Uwaga
    color: red
  note:
    title: Wskazówka
    color: purple
  highlight:
    title: Ćwiczenie
    color: yellow
  new:
    title: Ciekawostka
    color: green


