title: Ruby Knowledge Base
description: Ruby Knowledge Base
theme: just-the-docs
logo: "/assets/images/logo.png"
url: https://rosesz.github.io/rubybase

callouts:
  warning:
    title: Uwaga
    color: red
  note:
    title: Wskazówka
    color: purple
  highlight:
    title: Ćwiczenie
    color: yellow
  new:
    title: Ciekawostka
    color: green


