title: Ruby Knowledge Base
description: Ruby Knowledge Base
theme: just-the-docs
logo: "/images/logo.png"
url: https://rosesz.github.io/rubybase
footer_content: "with ♥ by <a href=\"https://github.com/rosesz\">rosesz</a>"

callouts:
  warning:
    title: Uwaga
    color: red
  note:
    title: Wskazówka
    color: purple
  highlight:
    title: Ćwiczenie
    color: yellow
  new:
    title: Ciekawostka
    color: green


